# apis/transaction_service/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY share/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY .env .env
COPY share/utilities/ utilities/
COPY apis/transaction_service/ .

RUN python manage.py makemigrations transaction_service
RUN python manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
